### ISSUE TITLE
Current Version not available via NPM

### ISSUE THREAD

**Issue by FroeMic** [antonlegoo/gitbook-plugin-theme-gestalt#3]
I would really need the *baseURL* feature of `1.0.4`.
As of now the latest release via npm – and thus the latest release that can be installed via `gitbook install` is `1.0.2`.

Could you please release the `1.0.4` via npm?

Thanks!

**Comment by antonlegoo** [comment]
Version `1.0.5` should now be available on npm.

( sorry for the delay, just got back from vacation )

**Comment by FroeMic** [comment]
Thanks!!
