### ISSUE TITLE
Missing font-awesome on assets

### ISSUE THREAD

**Issue by otavio** [antonlegoo/gitbook-plugin-theme-gestalt#4]
> HTTP/1.1 404 Not Found
> X-Current-Location: /fonts/fontawesome-webfont.ttf?v=4.6.3
> Date: Thu, 14 Dec 2017 17:48:23 GMT
> Connection: keep-alive
> Content-Length: 109

**Comment by otavio** [comment]
Looking at the code, it seems `npm` is not including the _assets directory and this is specifically where you copy the fonts.

**Comment by antonlegoo** [comment]
@otavio thanks for submitting this. Version 1.0.6 should now fix the issue.

Turns out it was a file path issue. Gitbook doesn't copy theme assets to the `_assets` folder, but instead places them in the `gitbook` folder. I've updated the font file path in the css which solves the issue in my tests.
