### ISSUE TITLE
Fonts URL is Relative instead of Absolute

### ISSUE THREAD

**Issue by michaeltlombardi** [antonlegoo/gitbook-plugin-theme-gestalt#5]
I've been playing around with the gestalt theme recently and noticed that the fontawesome icons weren't showing correctly - I had to go in and alter the path to the font files from `./gitbook/...` to `/gitbook/...`.

Running a build without any changes:

![Errors with file paths](https://user-images.githubusercontent.com/14190564/36443030-3f2fdeb6-163d-11e8-8a9e-3d3fdc99138c.png)

Fontawesome icons not rendering:

![Fontawesome icons not rendering](https://user-images.githubusercontent.com/14190564/36443051-4de25330-163d-11e8-8885-faf136edd40f.png)

This is the combiled `gitbook/style.css`:
![Compiled `gitbook/style.css`](https://user-images.githubusercontent.com/14190564/36443081-60f8ae1a-163d-11e8-96b4-3adb9aa2d662.png)

And then I update `gitbook/style.css`:

![Visible icons](https://user-images.githubusercontent.com/14190564/36443119-8013165a-163d-11e8-81dd-a4b09b23d21e.png)

And here's the `gitbook/style.css` after my 'fix':

![Fixed `gitbook/style.css`](https://user-images.githubusercontent.com/14190564/36443143-904bfae6-163d-11e8-93dd-296dd4cda607.png)

For reference, here's the gitbook config:

```json
{
  "plugins": ["theme-gestalt", "expandable-chapters"],
  "pluginsConfig": {
    "theme-gestalt": {
        "logo": "/img/logo.png",
        "favicon": "/img/favicon.png",
        "doNotHideChildrenChapters" : true
    }
  },
  "root": "docs"
}
```

**Comment by michaeltlombardi** [comment]
It looks like that is related to [this line](https://github.com/antonlegoo/gitbook-plugin-theme-gestalt/blob/04c56b82d73f68dc6e450b56170ae971a1f02b64/src/scss/website/font-awesome/_variables.scss#L4) which sets the `$fa-font-path`.

**Comment by antonlegoo** [comment]
@michaeltlombardi thanks for pointing this out. I've made an update that makes the Font Awesome path a variable. So in your `website.scss` you can overwrite the path such as:
```
@import "../node_modules/gitbook-plugin-theme-gestalt/src/scss/variables";

$path-font-awesome : "/gitbook/fonts/fontawesome";

@import "../node_modules/gitbook-plugin-theme-gestalt/src/scss/all";
```

**Comment by michaeltlombardi** [comment]
Awesome, thanks! :)
